nelmio_cors:
    paths:
        '^/schedule':
            allow_origin: ['http://127.0.0.1:5500']
            allow_methods: ['GET', 'POST']
            allow_headers: ['Content-Type']
            max_age: 3600